server:
  type: simple
  applicationContextPath: /
  connector:
    type: http
    port: 8080

database:
  # the name of your JDBC driver
  driverClass: org.postgresql.Driver

  # the JDBC URL
  url: jdbc:postgresql://ec2-54-247-189-141.eu-west-1.compute.amazonaws.com:5432/d3eur2mo3lln8v?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory

  #  the username
  user: nnquoatkxcxxtt

  # the password
  password: 44334bb19231f4dbf9fb33e9ec2627df9f5ef1856073de42130fce50a5a90e82

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s

  # the minimum number of connections to keep open
  minSize: 8

  # the maximum number of connections to keep open
  maxSize: 32

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false

  # the amount of time to sleep between runs of the idle connection validation, abandoned cleaner and idle pool resizing
  evictionInterval: 10s

  # the minimum amount of time an connection must sit idle in the pool before it is eligible for eviction
  minIdleTime: 1 minute

  properties:
       hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
       hibernate.generate_statistics: true
       hibernate.show_sql: true
       hibernate.format_sql: true
       hibernate.hbm2ddl.auto: update

swagger:
  resourcePackage: rs.elfak.bobans.carsharing.be.resources